STUDENT PERFORMANCE INDICATOR

In [24]:
#libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [25]:
#DataSet

data=pd.read_csv('data/stud.csv')
data.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [26]:
## Sahpe of dataset
data.shape

(1000, 8)

### 2.2 Dataset information



- gender : Male/female
- race/ethnicity : ethnicity of students -> (Group A,B,C,D,E)
- parental level of education : parents' final education ->(bachelor's degree,some college,master's degree,associate's degree,high school)
- lunch : having lunch before test (standard or free/reduced) 
- test preparation course : complete or not complete before test
- math score
- reading score
- writing score

### 3. Data Checks to perform

- Check Missing values
- Check Duplicates
- Check data type
- Check the number of unique values of each column
- Check statistics of data set
- Check various categories present in the different categorical column

In [27]:
#Check Missing values
data.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [28]:
# Check Duplicates
data.duplicated().sum()

np.int64(0)

In [29]:
#data types
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [30]:
#numer of unique value sin each row
data.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [31]:
#statistics of dataset
data.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [32]:
data.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [33]:
#various categories present in the different category column

print("categorys in gender column is ", end=" ")
print(data['gender'].unique())

print("categorys in 	race_ethnicity column is ", end=" ")
print(data['race_ethnicity'].unique())

print("categorys in parental_level_of_education column is ", end=" ")
print(data['parental_level_of_education'].unique())

print("categorys in lunch column is ", end=" ")
print(data['lunch'].unique())

print("categorys in test_preparation_course column is ", end=" ")
print(data['test_preparation_course'].unique())

categorys in gender column is  ['female' 'male']
categorys in 	race_ethnicity column is  ['group B' 'group C' 'group A' 'group D' 'group E']
categorys in parental_level_of_education column is  ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
categorys in lunch column is  ['standard' 'free/reduced']
categorys in test_preparation_course column is  ['none' 'completed']

In [34]:
## numerica and categorycal columns
num_features=[ features for features in data.columns if data[features].dtype!='O']
cat_features=[ features for features in data.columns if data[features].dtype=='O']

In [35]:
print(f"we have {len(num_features)} numerical features {num_features}")
print(f"\n we have {len(cat_features)} categorical features {cat_features}")

we have 3 numerical features ['math_score', 'reading_score', 'writing_score']

 we have 5 categorical features ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

### 3.8 Adding columns for "Total Score" and "Average"

In [37]:
data['total score']=data['math_score']+data['reading_score']+data['writing_score']
data['average_score']=data['total score']/3
data.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [41]:
reading=data[data['reading_score']>=90]['average_score'].count()
writing=data[data['writing_score']>=90]['average_score'].count()
maths=data[data['math_score']>=90]['average_score'].count()

print(f'numer of student who have marks greter than 90  in maths::{maths}')
print(f'numer of student who have marks greter than 90  in reading::{reading}')
print(f'numer of student who have marks greter than 90 in writing::{writing}')

numer of student who have marks greter than 90  in maths::58
numer of student who have marks greter than 90  in reading::79
numer of student who have marks greter than 90 in writing::78

In [42]:
reading=data[data['reading_score']<=20]['average_score'].count()
writing=data[data['writing_score']<=20]['average_score'].count()
maths=data[data['math_score']<=20]['average_score'].count()

print(f'numer of student who have marks less tha 20  in maths::{maths}')
print(f'numer of student who have reading less tha 20 in reading::{reading}')
print(f'numer of student who have writing less tha 20 in writing::{writing}')

numer of student who have marks less tha 20  in maths::4
numer of student who have reading less tha 20 in reading::1
numer of student who have writing less tha 20 in writing::3

#####  Insights
 - From above values we get students have performed the worst in Maths 
 - Best performance is in reading section